# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
    paypal_secret: '%env(PAYPAL_SECRET)%'
    paypal_mode: '%env(PAYPAL_MODE)%'
    paypal_webhook_id: '%env(PAYPAL_WEBHOOK_ID)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $env: '%kernel.environment%'

    App\:
        resource: '../src/'

    App\Service\StripeService:
        arguments:
            $secretKey: '%stripe_secret_key%'

    App\Controller\PaymentMethodController:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
        tags: ['controller.service_arguments']

    App\Service\PayPalService:
        arguments:
            $clientId: '%paypal_client_id%'
            $secret: '%paypal_secret%'
            $mode: '%paypal_mode%'
            $webhookId: '%paypal_webhook_id%'
