security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: false
            lazy: true

            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

            logout:
                path: /api/logout

        main:
            security: false

    access_control:
        # 🔓 Routes publiques
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/services, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: PUBLIC_ACCESS }

        # 🔐 Routes admin
        - { path: ^/api/admin, roles: ROLE_ADMIN }

        # 🔐 Routes authentifiées
        - { path: ^/api/me, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
